import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1740193662787 implements MigrationInterface {
    name = 'Init1740193662787'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "privilegios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "entidad" character varying NOT NULL, "leer" boolean NOT NULL DEFAULT true, "crear" boolean NOT NULL DEFAULT false, "actualizar" boolean NOT NULL DEFAULT false, "eliminar" boolean NOT NULL DEFAULT false, "admin" boolean NOT NULL DEFAULT false, "rolId" uuid, CONSTRAINT "PK_4784c2bdf68049d4cca1e0ae9e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying NOT NULL, "descripcion" character varying, CONSTRAINT "UQ_a5be7aa67e759e347b1c6464e10" UNIQUE ("nombre"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "paises" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying(100) NOT NULL, "name" character varying(100) NOT NULL, "iso2" character varying(2) NOT NULL, "iso3" character varying(3) NOT NULL, "phoneCode" character varying(10), CONSTRAINT "UQ_8a6179494dc1de9e839de612925" UNIQUE ("nombre"), CONSTRAINT "UQ_7ac231d9a191170cb5358845abb" UNIQUE ("name"), CONSTRAINT "UQ_e85ea6823e8b791b2d172c5711a" UNIQUE ("iso2"), CONSTRAINT "UQ_5bb9a2c1cda1ef5c084875f3775" UNIQUE ("iso3"), CONSTRAINT "PK_6b10c7997f3076c02e73c63b043" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "personas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "email" character varying(100) NOT NULL, "seudonimo" character varying(30), "empresa" character varying(100), "nombre" character varying(30), "apellido" character varying(30), "nif" character varying(30), "notas" character varying(500), "avatar" character varying(50), "telefono" character varying(20), "paisId" uuid, CONSTRAINT "UQ_6019651944f62d09f56ff66f600" UNIQUE ("email"), CONSTRAINT "UQ_01eb23ebdb742ab85fe83e73d15" UNIQUE ("seudonimo"), CONSTRAINT "UQ_2c5f388d06ec24b2e634f4ab2d9" UNIQUE ("nif"), CONSTRAINT "PK_714aa5d028f8f3e6645e971cecd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "direcciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "alias" character varying(50), "destinatario" character varying, "region" character varying(50), "ciudad" character varying(50), "codigoPostal" character varying(10), "calle" character varying(50), "unidad" character varying(50), "latitude" real, "longitude" real, "paisId" uuid, "personaId" uuid, CONSTRAINT "PK_7c30291ec345d647f94086e676d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "almacenes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying(50) NOT NULL, "direccionId" uuid, "paisId" uuid, CONSTRAINT "UQ_almacen_nombre_pais" UNIQUE ("nombre", "paisId"), CONSTRAINT "REL_385f67b0c618c8938a1537632a" UNIQUE ("direccionId"), CONSTRAINT "PK_2af9818dc2019bc97c7d26217e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sucursales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying(100) NOT NULL, "impuesto" numeric(10,2) NOT NULL DEFAULT '0', "impuestoIncluido" boolean NOT NULL DEFAULT false, "simboloMoneda" character varying(5) NOT NULL DEFAULT '$', "codigoMoneda" character varying(5) NOT NULL DEFAULT 'USD', "paisId" uuid, "direccionId" uuid, CONSTRAINT "UQ_sucursal_nombre_pais" UNIQUE ("nombre", "paisId"), CONSTRAINT "REL_ad14d4354756fbfaccc16904a7" UNIQUE ("direccionId"), CONSTRAINT "PK_c2232960c9e458db5b18d35eeba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."archivos_estatus_enum" AS ENUM('pendiente', 'cargando', 'cargado', 'error')`);
        await queryRunner.query(`CREATE TABLE "archivos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying(100) NOT NULL, "tipo" character varying(50) NOT NULL, "estatus" "public"."archivos_estatus_enum" NOT NULL DEFAULT 'cargado', "url" text NOT NULL, CONSTRAINT "PK_5609463cf53fb524304c926ad2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "email" character varying(100) NOT NULL, "seudonimo" character varying(30), "empresa" character varying(100), "nombre" character varying(30), "apellido" character varying(30), "nif" character varying(30), "notas" character varying(500), "avatar" character varying(50), "telefono" character varying(20), "password" character varying NOT NULL, "super" boolean NOT NULL DEFAULT false, "exw" boolean NOT NULL DEFAULT false, "balance" numeric(10,2) NOT NULL DEFAULT '0', "paisId" uuid, "rolId" uuid, CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5" UNIQUE ("email"), CONSTRAINT "UQ_8fd55f0d60c0c029731570bbe2b" UNIQUE ("seudonimo"), CONSTRAINT "UQ_aa11c9c2bf295cb819fafa0e49b" UNIQUE ("nif"), CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."producto_precios_tipodescuento_enum" AS ENUM('Porcentual', 'Absoluto')`);
        await queryRunner.query(`CREATE TABLE "producto_precios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "precioLista" numeric(10,2) NOT NULL DEFAULT '0', "precioOferta" numeric(10,2) NOT NULL DEFAULT '0', "precioExw" numeric(10,2) NOT NULL DEFAULT '0', "enOferta" boolean NOT NULL DEFAULT false, "inicioOferta" TIMESTAMP, "finOferta" TIMESTAMP, "descuento" numeric(10,2) NOT NULL DEFAULT '0', "tipoDescuento" "public"."producto_precios_tipodescuento_enum" NOT NULL DEFAULT 'Porcentual', "productoId" uuid, "paisId" uuid, CONSTRAINT "UQ_precio_producto_pais" UNIQUE ("productoId", "paisId"), CONSTRAINT "PK_36a14d631869130e648c8038be7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dimensiones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "largo" numeric(10,2) NOT NULL DEFAULT '0', "ancho" numeric(10,2) NOT NULL DEFAULT '0', "alto" numeric(10,2) NOT NULL DEFAULT '0', "peso" numeric(10,2) NOT NULL DEFAULT '0', "unidadLongitud" character varying(5) NOT NULL DEFAULT 'cm', "unidadPeso" character varying(5) NOT NULL DEFAULT 'kg', CONSTRAINT "PK_701f687a888169b72786136a84a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "producto_stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "actual" integer NOT NULL DEFAULT '0', "reservado" integer NOT NULL DEFAULT '0', "transito" integer NOT NULL DEFAULT '0', "rma" integer NOT NULL DEFAULT '0', "productoId" uuid, "almacenId" uuid, CONSTRAINT "UQ_stock_producto_almacen" UNIQUE ("productoId", "almacenId"), CONSTRAINT "PK_9aa935de752f81fd328bce176bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "producto_motores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "cantidad" integer NOT NULL DEFAULT '1', "productoId" uuid, "motorId" uuid, CONSTRAINT "PK_f4cc2b791a84003dc73afdd05cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subcategorias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying(100) NOT NULL, "name" character varying(100) NOT NULL, "orden" integer NOT NULL DEFAULT '0', "categoriaId" uuid, CONSTRAINT "PK_9bbef90f7112e787d4e4b23d455" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categorias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying(100) NOT NULL, "name" character varying(100) NOT NULL, "orden" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_ccdf6cd1a34ea90a7233325063d" UNIQUE ("nombre"), CONSTRAINT "UQ_b811b5f05010a79aa924ca84a3b" UNIQUE ("name"), CONSTRAINT "PK_3886a26251605c571c6b4f861fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "productos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying(100) NOT NULL, "descripcion" character varying, "costo" numeric(10,2), "sku" character varying(30) NOT NULL, "upc" character varying(30), "ean" character varying(30), "isbn" character varying(30), "requiereMotor" boolean NOT NULL DEFAULT false, "modelo" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "garantia" character varying NOT NULL DEFAULT 'Sin Garantía', "dimensionesId" uuid, "embalajeId" uuid, "portadaId" uuid, "categoriaId" uuid, "subcategoriaId" uuid, CONSTRAINT "UQ_805687bf24c1411756fbd37b2f3" UNIQUE ("sku"), CONSTRAINT "UQ_39ad874117a2e61ff36d118d03f" UNIQUE ("upc"), CONSTRAINT "UQ_bf0f1cc6349e4fa231f6e2e2434" UNIQUE ("ean"), CONSTRAINT "UQ_6e860633ffe10546864aa815b8a" UNIQUE ("isbn"), CONSTRAINT "REL_371de83bd89d4002dd34234ab2" UNIQUE ("dimensionesId"), CONSTRAINT "REL_c726cc5f660222e4216ec924a7" UNIQUE ("embalajeId"), CONSTRAINT "REL_4b39cdbdf267e53f6721d6a565" UNIQUE ("portadaId"), CONSTRAINT "PK_04f604609a0949a7f3b43400766" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "producto_traducciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "nombre" character varying(100) NOT NULL, "descripcion" character varying, "modelo" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "productoId" uuid, CONSTRAINT "REL_6f525e2886a0c4554fd209f8f0" UNIQUE ("productoId"), CONSTRAINT "PK_4d4399ebff81b2c8ac9b97ddffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transacciones_tipo_enum" AS ENUM('Factura', 'Débito', 'Avance de Efectivo', 'Pago', 'Crédito', 'Reembolso')`);
        await queryRunner.query(`CREATE TYPE "public"."transacciones_estatuspago_enum" AS ENUM('Pendiente', 'Confirmado', 'Rechazado', 'Cancelado', 'Fallido')`);
        await queryRunner.query(`CREATE TYPE "public"."transacciones_metodopago_enum" AS ENUM('Tarjeta de Crédito o Débito', 'Cheque', 'Depósito', 'Transferencia', 'Zelle', 'PayPal', 'Stripe', 'Remesa', 'Criptomoneda')`);
        await queryRunner.query(`CREATE TABLE "transacciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "referencia" SERIAL NOT NULL, "descripcion" text NOT NULL, "monto" numeric(10,2) NOT NULL, "balance" numeric(10,2) NOT NULL, "tipo" "public"."transacciones_tipo_enum" NOT NULL, "estatusPago" "public"."transacciones_estatuspago_enum", "metodoPago" "public"."transacciones_metodopago_enum", "qbInvoiceId" character varying, "qbInvoiceDocNumber" character varying, "usuarioId" uuid, CONSTRAINT "PK_0a2c5d8bfe49d3bbccff3f17e8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orden_items_qbtipoinventario_enum" AS ENUM('Inventory', 'NonInventory', 'Service', 'Bundle')`);
        await queryRunner.query(`CREATE TYPE "public"."orden_items_garantia_enum" AS ENUM('Sin Garantía', 'Seis Meses', 'Un Año', 'Dos Años')`);
        await queryRunner.query(`CREATE TABLE "orden_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "cantidad" integer NOT NULL DEFAULT '1', "precio" numeric(10,2) NOT NULL, "precioLista" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "qbTipoInventario" "public"."orden_items_qbtipoinventario_enum" NOT NULL DEFAULT 'Inventory', "notas" text, "garantia" "public"."orden_items_garantia_enum" NOT NULL DEFAULT 'Sin Garantía', "productoId" uuid, "almacenId" uuid, "ordenId" uuid, CONSTRAINT "PK_2e5335f80323aa222772a27d13d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."envios_transportista_enum" AS ENUM('DHL', 'UPS', 'FedEx', 'TNT', 'Marítimo', 'Terrestre', 'Otro')`);
        await queryRunner.query(`CREATE TABLE "envios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "notas" text, "transportista" "public"."envios_transportista_enum" NOT NULL, "tracking" character varying NOT NULL, CONSTRAINT "PK_c3e39ce11196eaf350b50652227" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orden_historial_estatus_enum" AS ENUM('Pendiente', 'Aprobado', 'Rechazado', 'Confirmado', 'Procesando', 'Enviado', 'Recibido', 'Entregado', 'Cancelado', 'Cerrado')`);
        await queryRunner.query(`CREATE TABLE "orden_historial" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "estatus" "public"."orden_historial_estatus_enum" NOT NULL, "notas" text, "usuarioId" uuid, "envioId" uuid, "ordenId" uuid, CONSTRAINT "PK_d37fb8cd995da5c11d95993e381" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ordenes_estatus_enum" AS ENUM('Pendiente', 'Aprobado', 'Rechazado', 'Confirmado', 'Procesando', 'Enviado', 'Recibido', 'Entregado', 'Cancelado', 'Cerrado')`);
        await queryRunner.query(`CREATE TYPE "public"."ordenes_tipo_enum" AS ENUM('Compra', 'Crédito', 'Reposición', 'Cotización')`);
        await queryRunner.query(`CREATE TYPE "public"."ordenes_tipodescuento_enum" AS ENUM('Porcentual', 'Absoluto')`);
        await queryRunner.query(`CREATE TABLE "ordenes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "serial" SERIAL NOT NULL, "estatus" "public"."ordenes_estatus_enum" NOT NULL DEFAULT 'Pendiente', "tipo" "public"."ordenes_tipo_enum" NOT NULL DEFAULT 'Compra', "validez" integer NOT NULL DEFAULT '15', "credito" numeric(10,2) DEFAULT '0', "descuento" numeric(10,2) DEFAULT '0', "tipoDescuento" "public"."ordenes_tipodescuento_enum" DEFAULT 'Porcentual', "impuestoIncluido" boolean NOT NULL DEFAULT false, "impuesto" numeric(10,2) NOT NULL DEFAULT '0', "subtotal" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "totalLista" numeric(10,2) NOT NULL, "notas" text, "qbInvoiceId" character varying, "qbInvoiceDocNumber" character varying, "sucursalId" uuid, "vendedorId" uuid, "clienteId" uuid, CONSTRAINT "PK_58713affeb8e3b7b30b9eeeee7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invitaciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "email" character varying(255) NOT NULL, "nombre" character varying(50) NOT NULL, "apellido" character varying(50) NOT NULL, "estatus" character varying(20) NOT NULL, "token" character varying(50) NOT NULL, "rolId" uuid, CONSTRAINT "UQ_d081337f1012a51cda5543c200a" UNIQUE ("email"), CONSTRAINT "PK_224c1573f98dbf3c1c825bc447f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "certificados" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "serial" SERIAL NOT NULL, "itemId" uuid, "ordenId" uuid, CONSTRAINT "REL_afdd61b8f1604f6f3402d9383b" UNIQUE ("itemId"), CONSTRAINT "PK_e9b232ca7a16db08667f021708f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "apps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activo" boolean NOT NULL DEFAULT true, "fechaCreado" TIMESTAMP NOT NULL DEFAULT now(), "fechaActualizado" TIMESTAMP NOT NULL DEFAULT now(), "fechaEliminado" TIMESTAMP, "name" character varying(50) NOT NULL, "description" character varying(120) NOT NULL, "clientId" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientSecret" uuid NOT NULL DEFAULT uuid_generate_v4(), "redirectUri" text NOT NULL, CONSTRAINT "PK_c5121fda0f8268f1f7f84134e19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sucursales_almacenes" ("sucursalesId" uuid NOT NULL, "almacenesId" uuid NOT NULL, CONSTRAINT "PK_569dc3ab82e89e7a78365e43ce0" PRIMARY KEY ("sucursalesId", "almacenesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c889c8e5e78b2a11ae5a5be95" ON "sucursales_almacenes" ("sucursalesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8091728c3c9afc8684bcc2dd8" ON "sucursales_almacenes" ("almacenesId") `);
        await queryRunner.query(`CREATE TABLE "usuarios_sucursales" ("usuariosId" uuid NOT NULL, "sucursalesId" uuid NOT NULL, CONSTRAINT "PK_fb425aa335b740d517028e01c9f" PRIMARY KEY ("usuariosId", "sucursalesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac6c269d10970c1e2377d0e152" ON "usuarios_sucursales" ("usuariosId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff0c79ec1437d1380fd34d2670" ON "usuarios_sucursales" ("sucursalesId") `);
        await queryRunner.query(`CREATE TABLE "usuarios_archivos" ("usuariosId" uuid NOT NULL, "archivosId" uuid NOT NULL, CONSTRAINT "PK_89548d29c3cea81ca46aeec423a" PRIMARY KEY ("usuariosId", "archivosId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_866fc3dc397eb52d88400e061b" ON "usuarios_archivos" ("usuariosId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7a54cf7fb0e11409c1f2252c4" ON "usuarios_archivos" ("archivosId") `);
        await queryRunner.query(`CREATE TABLE "productos_galeria_archivos" ("productosId" uuid NOT NULL, "archivosId" uuid NOT NULL, CONSTRAINT "PK_b55e10fe6b65e0a24433bb748cd" PRIMARY KEY ("productosId", "archivosId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2f928a821061cfcf913d4b0c3c" ON "productos_galeria_archivos" ("productosId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ee0e7dc44852971926eb1c7936" ON "productos_galeria_archivos" ("archivosId") `);
        await queryRunner.query(`CREATE TABLE "productos_paises_paises" ("productosId" uuid NOT NULL, "paisesId" uuid NOT NULL, CONSTRAINT "PK_2fdb7099c18599ee51422009e56" PRIMARY KEY ("productosId", "paisesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38a3aa588847be3c137d171eb4" ON "productos_paises_paises" ("productosId") `);
        await queryRunner.query(`CREATE INDEX "IDX_90a8971191b1aa1a1c0b967dd8" ON "productos_paises_paises" ("paisesId") `);
        await queryRunner.query(`CREATE TABLE "transaccion_archivos" ("transaccionId" uuid NOT NULL, "archivoId" uuid NOT NULL, CONSTRAINT "PK_083cebd26eb37c49980045054ff" PRIMARY KEY ("transaccionId", "archivoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a4d5bb5de168c8a29d032e71b" ON "transaccion_archivos" ("transaccionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_11570fb0510f28f35c10f99709" ON "transaccion_archivos" ("archivoId") `);
        await queryRunner.query(`CREATE TABLE "orden_items_archivos" ("ordenItemsId" uuid NOT NULL, "archivosId" uuid NOT NULL, CONSTRAINT "PK_319c35a9b3853a551ff7745c0d7" PRIMARY KEY ("ordenItemsId", "archivosId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed183349eacb1a51fa56a2b247" ON "orden_items_archivos" ("ordenItemsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_37b5e9cbab91f5fae6735afc1c" ON "orden_items_archivos" ("archivosId") `);
        await queryRunner.query(`CREATE TABLE "orden_archivos" ("ordenesId" uuid NOT NULL, "archivosId" uuid NOT NULL, CONSTRAINT "PK_dd0a3d4239ae3e10b4bafe6dfc4" PRIMARY KEY ("ordenesId", "archivosId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b61c643a1fdf2afb6af5dea787" ON "orden_archivos" ("ordenesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b050dbb76f823c1534e6ce8b2e" ON "orden_archivos" ("archivosId") `);
        await queryRunner.query(`CREATE TABLE "orden_envios" ("ordenesId" uuid NOT NULL, "enviosId" uuid NOT NULL, CONSTRAINT "PK_c547627219593fd7ed96adca2a1" PRIMARY KEY ("ordenesId", "enviosId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1cb71c54f82eb57bc7bf90c1eb" ON "orden_envios" ("ordenesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f0ff4883a4b6803f446d1d4bf" ON "orden_envios" ("enviosId") `);
        await queryRunner.query(`ALTER TABLE "privilegios" ADD CONSTRAINT "FK_1a3b7bdf64afa935e92b3d24b6f" FOREIGN KEY ("rolId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personas" ADD CONSTRAINT "FK_98036ea4eb08f1bb301dd2c0413" FOREIGN KEY ("paisId") REFERENCES "paises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "direcciones" ADD CONSTRAINT "FK_a79b63ff978476c2c9b349a30ab" FOREIGN KEY ("paisId") REFERENCES "paises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "direcciones" ADD CONSTRAINT "FK_ab662d16713a6461e97c8422670" FOREIGN KEY ("personaId") REFERENCES "personas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "almacenes" ADD CONSTRAINT "FK_385f67b0c618c8938a1537632ae" FOREIGN KEY ("direccionId") REFERENCES "direcciones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "almacenes" ADD CONSTRAINT "FK_a744523062f21da1549daf1d61a" FOREIGN KEY ("paisId") REFERENCES "paises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sucursales" ADD CONSTRAINT "FK_9083d57b43975e9ef43167ea3df" FOREIGN KEY ("paisId") REFERENCES "paises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sucursales" ADD CONSTRAINT "FK_ad14d4354756fbfaccc16904a7c" FOREIGN KEY ("direccionId") REFERENCES "direcciones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_766d191a29c69c76857688c6619" FOREIGN KEY ("paisId") REFERENCES "paises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_df0c94be5a01a546bf1b9ca12ae" FOREIGN KEY ("rolId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto_precios" ADD CONSTRAINT "FK_6d81385a69f2617b4a2d853c764" FOREIGN KEY ("productoId") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto_precios" ADD CONSTRAINT "FK_ec28d285ba0d4d8d4cf3e5e368a" FOREIGN KEY ("paisId") REFERENCES "paises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto_stock" ADD CONSTRAINT "FK_5205e9b69b4d9702e34e7220cad" FOREIGN KEY ("productoId") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto_stock" ADD CONSTRAINT "FK_3436ff392b4517494a2c018da80" FOREIGN KEY ("almacenId") REFERENCES "almacenes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto_motores" ADD CONSTRAINT "FK_c278595d277f59a974d9c7adb06" FOREIGN KEY ("productoId") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto_motores" ADD CONSTRAINT "FK_4e7554f01c4cf73288d7ef0dbf7" FOREIGN KEY ("motorId") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcategorias" ADD CONSTRAINT "FK_55b0166e1926780a24cdda43be0" FOREIGN KEY ("categoriaId") REFERENCES "categorias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "FK_371de83bd89d4002dd34234ab21" FOREIGN KEY ("dimensionesId") REFERENCES "dimensiones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "FK_c726cc5f660222e4216ec924a71" FOREIGN KEY ("embalajeId") REFERENCES "dimensiones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "FK_4b39cdbdf267e53f6721d6a5656" FOREIGN KEY ("portadaId") REFERENCES "archivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "FK_aee00189e42dd8880cdfe1bb1e7" FOREIGN KEY ("categoriaId") REFERENCES "categorias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "FK_8608d0b376af6c80dc272d323c6" FOREIGN KEY ("subcategoriaId") REFERENCES "subcategorias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producto_traducciones" ADD CONSTRAINT "FK_6f525e2886a0c4554fd209f8f06" FOREIGN KEY ("productoId") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transacciones" ADD CONSTRAINT "FK_5177666e7d85390208261d069ba" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orden_items" ADD CONSTRAINT "FK_f95f86d117ff1fb42ebcb07f9c9" FOREIGN KEY ("productoId") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orden_items" ADD CONSTRAINT "FK_2c3ad3f6c20aea8b5165959dd1c" FOREIGN KEY ("almacenId") REFERENCES "almacenes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orden_items" ADD CONSTRAINT "FK_e70bd783e604b6d7f35072d8513" FOREIGN KEY ("ordenId") REFERENCES "ordenes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orden_historial" ADD CONSTRAINT "FK_801b00ef7ab5d000d8b5dafc532" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orden_historial" ADD CONSTRAINT "FK_289876c121b4386543d93a343ce" FOREIGN KEY ("envioId") REFERENCES "envios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orden_historial" ADD CONSTRAINT "FK_080a2a7a66b27fd72306f3402d6" FOREIGN KEY ("ordenId") REFERENCES "ordenes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "FK_55779a0372a03320b217c5b6f91" FOREIGN KEY ("sucursalId") REFERENCES "sucursales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "FK_c2f8a3c376f9b150a7c87cc2542" FOREIGN KEY ("vendedorId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ordenes" ADD CONSTRAINT "FK_09e7c5c2a11a208941307638614" FOREIGN KEY ("clienteId") REFERENCES "personas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitaciones" ADD CONSTRAINT "FK_67c9aff337e410e457808519046" FOREIGN KEY ("rolId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificados" ADD CONSTRAINT "FK_afdd61b8f1604f6f3402d9383be" FOREIGN KEY ("itemId") REFERENCES "orden_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificados" ADD CONSTRAINT "FK_2abcef701acecde36b1d7c6e6cb" FOREIGN KEY ("ordenId") REFERENCES "ordenes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sucursales_almacenes" ADD CONSTRAINT "FK_8c889c8e5e78b2a11ae5a5be950" FOREIGN KEY ("sucursalesId") REFERENCES "sucursales"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sucursales_almacenes" ADD CONSTRAINT "FK_a8091728c3c9afc8684bcc2dd86" FOREIGN KEY ("almacenesId") REFERENCES "almacenes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuarios_sucursales" ADD CONSTRAINT "FK_ac6c269d10970c1e2377d0e152e" FOREIGN KEY ("usuariosId") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuarios_sucursales" ADD CONSTRAINT "FK_ff0c79ec1437d1380fd34d2670d" FOREIGN KEY ("sucursalesId") REFERENCES "sucursales"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuarios_archivos" ADD CONSTRAINT "FK_866fc3dc397eb52d88400e061bb" FOREIGN KEY ("usuariosId") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuarios_archivos" ADD CONSTRAINT "FK_c7a54cf7fb0e11409c1f2252c4a" FOREIGN KEY ("archivosId") REFERENCES "archivos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "productos_galeria_archivos" ADD CONSTRAINT "FK_2f928a821061cfcf913d4b0c3c1" FOREIGN KEY ("productosId") REFERENCES "productos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "productos_galeria_archivos" ADD CONSTRAINT "FK_ee0e7dc44852971926eb1c7936e" FOREIGN KEY ("archivosId") REFERENCES "archivos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "productos_paises_paises" ADD CONSTRAINT "FK_38a3aa588847be3c137d171eb48" FOREIGN KEY ("productosId") REFERENCES "productos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "productos_paises_paises" ADD CONSTRAINT "FK_90a8971191b1aa1a1c0b967dd8d" FOREIGN KEY ("paisesId") REFERENCES "paises"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transaccion_archivos" ADD CONSTRAINT "FK_5a4d5bb5de168c8a29d032e71b9" FOREIGN KEY ("transaccionId") REFERENCES "transacciones"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transaccion_archivos" ADD CONSTRAINT "FK_11570fb0510f28f35c10f997091" FOREIGN KEY ("archivoId") REFERENCES "archivos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orden_items_archivos" ADD CONSTRAINT "FK_ed183349eacb1a51fa56a2b2470" FOREIGN KEY ("ordenItemsId") REFERENCES "orden_items"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orden_items_archivos" ADD CONSTRAINT "FK_37b5e9cbab91f5fae6735afc1c7" FOREIGN KEY ("archivosId") REFERENCES "archivos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orden_archivos" ADD CONSTRAINT "FK_b61c643a1fdf2afb6af5dea7871" FOREIGN KEY ("ordenesId") REFERENCES "ordenes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orden_archivos" ADD CONSTRAINT "FK_b050dbb76f823c1534e6ce8b2e9" FOREIGN KEY ("archivosId") REFERENCES "archivos"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orden_envios" ADD CONSTRAINT "FK_1cb71c54f82eb57bc7bf90c1ebb" FOREIGN KEY ("ordenesId") REFERENCES "ordenes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orden_envios" ADD CONSTRAINT "FK_8f0ff4883a4b6803f446d1d4bf0" FOREIGN KEY ("enviosId") REFERENCES "envios"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "orden_envios" DROP CONSTRAINT "FK_8f0ff4883a4b6803f446d1d4bf0"`);
        await queryRunner.query(`ALTER TABLE "orden_envios" DROP CONSTRAINT "FK_1cb71c54f82eb57bc7bf90c1ebb"`);
        await queryRunner.query(`ALTER TABLE "orden_archivos" DROP CONSTRAINT "FK_b050dbb76f823c1534e6ce8b2e9"`);
        await queryRunner.query(`ALTER TABLE "orden_archivos" DROP CONSTRAINT "FK_b61c643a1fdf2afb6af5dea7871"`);
        await queryRunner.query(`ALTER TABLE "orden_items_archivos" DROP CONSTRAINT "FK_37b5e9cbab91f5fae6735afc1c7"`);
        await queryRunner.query(`ALTER TABLE "orden_items_archivos" DROP CONSTRAINT "FK_ed183349eacb1a51fa56a2b2470"`);
        await queryRunner.query(`ALTER TABLE "transaccion_archivos" DROP CONSTRAINT "FK_11570fb0510f28f35c10f997091"`);
        await queryRunner.query(`ALTER TABLE "transaccion_archivos" DROP CONSTRAINT "FK_5a4d5bb5de168c8a29d032e71b9"`);
        await queryRunner.query(`ALTER TABLE "productos_paises_paises" DROP CONSTRAINT "FK_90a8971191b1aa1a1c0b967dd8d"`);
        await queryRunner.query(`ALTER TABLE "productos_paises_paises" DROP CONSTRAINT "FK_38a3aa588847be3c137d171eb48"`);
        await queryRunner.query(`ALTER TABLE "productos_galeria_archivos" DROP CONSTRAINT "FK_ee0e7dc44852971926eb1c7936e"`);
        await queryRunner.query(`ALTER TABLE "productos_galeria_archivos" DROP CONSTRAINT "FK_2f928a821061cfcf913d4b0c3c1"`);
        await queryRunner.query(`ALTER TABLE "usuarios_archivos" DROP CONSTRAINT "FK_c7a54cf7fb0e11409c1f2252c4a"`);
        await queryRunner.query(`ALTER TABLE "usuarios_archivos" DROP CONSTRAINT "FK_866fc3dc397eb52d88400e061bb"`);
        await queryRunner.query(`ALTER TABLE "usuarios_sucursales" DROP CONSTRAINT "FK_ff0c79ec1437d1380fd34d2670d"`);
        await queryRunner.query(`ALTER TABLE "usuarios_sucursales" DROP CONSTRAINT "FK_ac6c269d10970c1e2377d0e152e"`);
        await queryRunner.query(`ALTER TABLE "sucursales_almacenes" DROP CONSTRAINT "FK_a8091728c3c9afc8684bcc2dd86"`);
        await queryRunner.query(`ALTER TABLE "sucursales_almacenes" DROP CONSTRAINT "FK_8c889c8e5e78b2a11ae5a5be950"`);
        await queryRunner.query(`ALTER TABLE "certificados" DROP CONSTRAINT "FK_2abcef701acecde36b1d7c6e6cb"`);
        await queryRunner.query(`ALTER TABLE "certificados" DROP CONSTRAINT "FK_afdd61b8f1604f6f3402d9383be"`);
        await queryRunner.query(`ALTER TABLE "invitaciones" DROP CONSTRAINT "FK_67c9aff337e410e457808519046"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "FK_09e7c5c2a11a208941307638614"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "FK_c2f8a3c376f9b150a7c87cc2542"`);
        await queryRunner.query(`ALTER TABLE "ordenes" DROP CONSTRAINT "FK_55779a0372a03320b217c5b6f91"`);
        await queryRunner.query(`ALTER TABLE "orden_historial" DROP CONSTRAINT "FK_080a2a7a66b27fd72306f3402d6"`);
        await queryRunner.query(`ALTER TABLE "orden_historial" DROP CONSTRAINT "FK_289876c121b4386543d93a343ce"`);
        await queryRunner.query(`ALTER TABLE "orden_historial" DROP CONSTRAINT "FK_801b00ef7ab5d000d8b5dafc532"`);
        await queryRunner.query(`ALTER TABLE "orden_items" DROP CONSTRAINT "FK_e70bd783e604b6d7f35072d8513"`);
        await queryRunner.query(`ALTER TABLE "orden_items" DROP CONSTRAINT "FK_2c3ad3f6c20aea8b5165959dd1c"`);
        await queryRunner.query(`ALTER TABLE "orden_items" DROP CONSTRAINT "FK_f95f86d117ff1fb42ebcb07f9c9"`);
        await queryRunner.query(`ALTER TABLE "transacciones" DROP CONSTRAINT "FK_5177666e7d85390208261d069ba"`);
        await queryRunner.query(`ALTER TABLE "producto_traducciones" DROP CONSTRAINT "FK_6f525e2886a0c4554fd209f8f06"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "FK_8608d0b376af6c80dc272d323c6"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "FK_aee00189e42dd8880cdfe1bb1e7"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "FK_4b39cdbdf267e53f6721d6a5656"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "FK_c726cc5f660222e4216ec924a71"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "FK_371de83bd89d4002dd34234ab21"`);
        await queryRunner.query(`ALTER TABLE "subcategorias" DROP CONSTRAINT "FK_55b0166e1926780a24cdda43be0"`);
        await queryRunner.query(`ALTER TABLE "producto_motores" DROP CONSTRAINT "FK_4e7554f01c4cf73288d7ef0dbf7"`);
        await queryRunner.query(`ALTER TABLE "producto_motores" DROP CONSTRAINT "FK_c278595d277f59a974d9c7adb06"`);
        await queryRunner.query(`ALTER TABLE "producto_stock" DROP CONSTRAINT "FK_3436ff392b4517494a2c018da80"`);
        await queryRunner.query(`ALTER TABLE "producto_stock" DROP CONSTRAINT "FK_5205e9b69b4d9702e34e7220cad"`);
        await queryRunner.query(`ALTER TABLE "producto_precios" DROP CONSTRAINT "FK_ec28d285ba0d4d8d4cf3e5e368a"`);
        await queryRunner.query(`ALTER TABLE "producto_precios" DROP CONSTRAINT "FK_6d81385a69f2617b4a2d853c764"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_df0c94be5a01a546bf1b9ca12ae"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_766d191a29c69c76857688c6619"`);
        await queryRunner.query(`ALTER TABLE "sucursales" DROP CONSTRAINT "FK_ad14d4354756fbfaccc16904a7c"`);
        await queryRunner.query(`ALTER TABLE "sucursales" DROP CONSTRAINT "FK_9083d57b43975e9ef43167ea3df"`);
        await queryRunner.query(`ALTER TABLE "almacenes" DROP CONSTRAINT "FK_a744523062f21da1549daf1d61a"`);
        await queryRunner.query(`ALTER TABLE "almacenes" DROP CONSTRAINT "FK_385f67b0c618c8938a1537632ae"`);
        await queryRunner.query(`ALTER TABLE "direcciones" DROP CONSTRAINT "FK_ab662d16713a6461e97c8422670"`);
        await queryRunner.query(`ALTER TABLE "direcciones" DROP CONSTRAINT "FK_a79b63ff978476c2c9b349a30ab"`);
        await queryRunner.query(`ALTER TABLE "personas" DROP CONSTRAINT "FK_98036ea4eb08f1bb301dd2c0413"`);
        await queryRunner.query(`ALTER TABLE "privilegios" DROP CONSTRAINT "FK_1a3b7bdf64afa935e92b3d24b6f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f0ff4883a4b6803f446d1d4bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cb71c54f82eb57bc7bf90c1eb"`);
        await queryRunner.query(`DROP TABLE "orden_envios"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b050dbb76f823c1534e6ce8b2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b61c643a1fdf2afb6af5dea787"`);
        await queryRunner.query(`DROP TABLE "orden_archivos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37b5e9cbab91f5fae6735afc1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed183349eacb1a51fa56a2b247"`);
        await queryRunner.query(`DROP TABLE "orden_items_archivos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11570fb0510f28f35c10f99709"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a4d5bb5de168c8a29d032e71b"`);
        await queryRunner.query(`DROP TABLE "transaccion_archivos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90a8971191b1aa1a1c0b967dd8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38a3aa588847be3c137d171eb4"`);
        await queryRunner.query(`DROP TABLE "productos_paises_paises"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee0e7dc44852971926eb1c7936"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f928a821061cfcf913d4b0c3c"`);
        await queryRunner.query(`DROP TABLE "productos_galeria_archivos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7a54cf7fb0e11409c1f2252c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_866fc3dc397eb52d88400e061b"`);
        await queryRunner.query(`DROP TABLE "usuarios_archivos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff0c79ec1437d1380fd34d2670"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac6c269d10970c1e2377d0e152"`);
        await queryRunner.query(`DROP TABLE "usuarios_sucursales"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8091728c3c9afc8684bcc2dd8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c889c8e5e78b2a11ae5a5be95"`);
        await queryRunner.query(`DROP TABLE "sucursales_almacenes"`);
        await queryRunner.query(`DROP TABLE "apps"`);
        await queryRunner.query(`DROP TABLE "certificados"`);
        await queryRunner.query(`DROP TABLE "invitaciones"`);
        await queryRunner.query(`DROP TABLE "ordenes"`);
        await queryRunner.query(`DROP TYPE "public"."ordenes_tipodescuento_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ordenes_tipo_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ordenes_estatus_enum"`);
        await queryRunner.query(`DROP TABLE "orden_historial"`);
        await queryRunner.query(`DROP TYPE "public"."orden_historial_estatus_enum"`);
        await queryRunner.query(`DROP TABLE "envios"`);
        await queryRunner.query(`DROP TYPE "public"."envios_transportista_enum"`);
        await queryRunner.query(`DROP TABLE "orden_items"`);
        await queryRunner.query(`DROP TYPE "public"."orden_items_garantia_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orden_items_qbtipoinventario_enum"`);
        await queryRunner.query(`DROP TABLE "transacciones"`);
        await queryRunner.query(`DROP TYPE "public"."transacciones_metodopago_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transacciones_estatuspago_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transacciones_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "producto_traducciones"`);
        await queryRunner.query(`DROP TABLE "productos"`);
        await queryRunner.query(`DROP TABLE "categorias"`);
        await queryRunner.query(`DROP TABLE "subcategorias"`);
        await queryRunner.query(`DROP TABLE "producto_motores"`);
        await queryRunner.query(`DROP TABLE "producto_stock"`);
        await queryRunner.query(`DROP TABLE "dimensiones"`);
        await queryRunner.query(`DROP TABLE "producto_precios"`);
        await queryRunner.query(`DROP TYPE "public"."producto_precios_tipodescuento_enum"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "archivos"`);
        await queryRunner.query(`DROP TYPE "public"."archivos_estatus_enum"`);
        await queryRunner.query(`DROP TABLE "sucursales"`);
        await queryRunner.query(`DROP TABLE "almacenes"`);
        await queryRunner.query(`DROP TABLE "direcciones"`);
        await queryRunner.query(`DROP TABLE "personas"`);
        await queryRunner.query(`DROP TABLE "paises"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "privilegios"`);
    }

}
